# 공통 컴파일러 및 도구 경로 설정 (절대 경로)
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/local_paths.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/local_paths.cmake")
else()
    include("${CMAKE_CURRENT_LIST_DIR}/default_paths.cmake")
endif()